# Generated by Django 6.1.1 on 2026-10-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRestaurante',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('whatsapp', models.CharField(blank=True, help_text='Número internacional, com DDI e DDD, somente dígitos.', max_length=15)),
            ],
            options={
                'verbose_name': 'configuração do restaurante',
                'verbose_name_plural': 'configuração do restaurante',
            },
        ),
    ]
