# Generated by Django 6.1.1 on 2026-10-03 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='map_embed_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='maps_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
    ]
