# Generated by Django 6.1.1 on 2026-10-03 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_configuracaorestaurante_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='facebook_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='instagram_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
    ]
