# Generated by Django 6.1.1 on 2026-10-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_configuracaorestaurante_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='carousel_image_1',
            field=models.ImageField(blank=True, upload_to='carousel/', verbose_name='Imagem 1 do carrossel'),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='carousel_image_2',
            field=models.ImageField(blank=True, upload_to='carousel/', verbose_name='Imagem 2 do carrossel'),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='carousel_image_3',
            field=models.ImageField(blank=True, upload_to='carousel/', verbose_name='Imagem 3 do carrossel'),
        ),
    ]
