# Generated by Django 6.1.1 on 2026-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_configuracaorestaurante_carousel_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='restaurant_logo',
            field=models.ImageField(blank=True, upload_to='restaurant/', verbose_name='Logo do restaurante'),
        ),
        migrations.AddField(
            model_name='configuracaorestaurante',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do restaurante'),
        ),
    ]
