# Generated by Django 6.1.1 on 2026-10-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['ordem', 'nome']},
        ),
    ]
